var InboxConstants = {
  RECEIVE_CLICKED_INBOX: "RECEIVE_CLICKED_INBOX",
  RECEIVE_CLICKED_LIST: "RECEIVE_CLICKED_LIST",
  RECEIVE_CLICKED_LOCATION: "RECEIVE_CLICKED_LOCATION"
};

module.exports = InboxConstants;
