var ListConstants = {
  RECEIVE_ALL_LISTS: "RECEIVE_ALL_LISTS",
  RECEIVE_NEW_LIST: "RECEIVE_NEW_LIST",
  RECEIVE_UPDATED_LIST: "RECEIVE_UPDATED_LIST",
  REMOVE_LIST: "REMOVE_LIST"
};

module.exports = ListConstants;
