var TaskConstants = {
  GET_ALL_TASKS: "GET_ALL_TASKS",
  GET_ALL_COMPLETED_TASKS: "GET_ALL_COMPLETED_TASKS",
  GET_INCOMPLETE_TASKS: "GET_INCOMPLETE_TASKS",
  GET_ONE_TASK: "GET_ONE_TASK",
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  COMPLETE_TASK: "COMPLETE_TASK",
  SET_STORE: "SET_STORE",
  HOLD_ALL_TASKS: "HOLD_ALL_TASKS",
  SET_CURRENT_INBOX_TASKS: "SET_CURRENT_INBOX_TASKS"
};

module.exports = TaskConstants;
