json.task_id task.id
json.owner_id task.owner_id
json.owner_username task.user.username
json.name task.name
json.completed task.completed
json.start_date task.start_date
json.due_date task.due_date
json.priority task.priority
json.estimate task.estimate
json.list_id task.list_id
json.location_id task.location_id
